Create chooseRepeat function
potyama/software_design pull request #21
Opened 2020-11-27 02:13 UTC by potyama

2020-11-28 05:47 UTC, onokatio requested changes

2020-11-28 05:47 UTC, onokatio commented on game.c
>  		    repeat=10;
インデント崩れてる

2020-11-28 09:09 UTC, potyama commented
修正しました

2020-12-04 01:10 UTC, WalkerZC approved these changes
オッケー

2020-12-04 01:28 UTC, onokatio approved these changes
LGTM

2020-12-04 01:28 UTC, merged